Update action.yml

diff --git a/.github/workflows/docs/generate-docs/action.yml b/.github/workflows/docs/generate-docs/action.yml
--- a/.github/workflows/docs/generate-docs/action.yml
+++ b/.github/workflows/docs/generate-docs/action.yml
@@ -62,25 +62,29 @@ runs:
           ./gradlew genNightlyDocs javadoc
         fi
 
-        mkdir -p "${SKRIPT_DOCS_OUTPUT_DIR}/javadocs" && cp -a "./build/docs/javadoc/." "$_"
+        if [ -d "${DOCS_OUTPUT_DIR}" ]; then
+          mkdir -p "${SKRIPT_DOCS_OUTPUT_DIR}/javadocs" && cp -a "./build/docs/javadoc/." "$_"
+  
+          mkdir -p "/tmp/normalized-output-docs" && cp -a "${DOCS_OUTPUT_DIR}/." "$_"
+          mkdir -p "/tmp/normalized-generated-docs" && cp -a "${SKRIPT_DOCS_OUTPUT_DIR}/." "$_"
+  
+          output_skript_version=$(get_skript_version_of_directory "/tmp/normalized-output-docs")
+          generated_skript_version=$(get_skript_version_of_directory "/tmp/normalized-generated-docs")
 
-        mkdir -p "/tmp/normalized-output-docs" && cp -a "${DOCS_OUTPUT_DIR}/." "$_"
-        mkdir -p "/tmp/normalized-generated-docs" && cp -a "${SKRIPT_DOCS_OUTPUT_DIR}/." "$_"
-
-        output_skript_version=$(get_skript_version_of_directory "/tmp/normalized-output-docs")
-        generated_skript_version=$(get_skript_version_of_directory "/tmp/normalized-generated-docs")
-        echo "Output skript ver: ${output_skript_version}"
-        echo "Generated skript ver: ${generated_skript_version}"
-        replace_in_directory "/tmp/normalized-output-docs" "${output_skript_version}" "Skript"
-        replace_in_directory "/tmp/normalized-generated-docs" "${generated_skript_version}" "Skript"
-
-        diff -qbr /tmp/normalized-output-docs /tmp/normalized-generated-docs || diff_exit_code=$?
-        # If diff exits with exit code 1, that means there were some differences
-        if [[ ${diff_exit_code} -eq 1 ]]; then
-          echo "DOCS_CHANGED=true" >> $GITHUB_OUTPUT
-          echo "Documentation has changed since last push"
+          replace_in_directory "/tmp/normalized-output-docs" "${output_skript_version}" "Skript"
+          replace_in_directory "/tmp/normalized-generated-docs" "${generated_skript_version}" "Skript"
+  
+          diff -qbr /tmp/normalized-output-docs /tmp/normalized-generated-docs || diff_exit_code=$?
+          # If diff exits with exit code 1, that means there were some differences
+          if [[ ${diff_exit_code} -eq 1 ]]; then
+            echo "DOCS_CHANGED=true" >> $GITHUB_OUTPUT
+            echo "Documentation has changed since last push"
+          else
+            echo "Documentation hasn't changed since last push"
+          fi
         else
-          echo "Documentation hasn't changed since last push"
+            echo "DOCS_CHANGED=true" >> $GITHUB_OUTPUT
+            echo "No existing documentation found"
         fi
         
         rm -rf ${DOCS_OUTPUT_DIR}/${CLEANUP_PATTERN} || true
