Update action.yml

diff --git a/.github/workflows/docs/generate-docs/action.yml b/.github/workflows/docs/generate-docs/action.yml
--- a/.github/workflows/docs/generate-docs/action.yml
+++ b/.github/workflows/docs/generate-docs/action.yml
@@ -68,14 +68,13 @@ runs:
         replace_in_directory "/tmp/normalized-output-docs" "${output_skript_version}" "Skript"
         replace_in_directory "/tmp/normalized-generated-docs" "${generated_skript_version}" "Skript"
 
-        diff -qr /tmp/normalized-output-docs /tmp/normalized-generated-docs
-        # If diff exists with exit code 1, that means there were some differences
+        diff -qr /tmp/normalized-output-docs /tmp/normalized-generated-docs || true > /dev/null
+        # If diff exits with exit code 1, that means there were some differences
         if [[ $? -eq 1 ]]; then
           echo "DOCS_CHANGED=true" >> "$GITHUB_OUTPUT"
         fi
         
         rm -rf ${DOCS_OUTPUT_DIR}/${CLEANUP_PATTERN} || true
         mkdir -p "${DOCS_OUTPUT_DIR}/" && cp -a "${SKRIPT_DOCS_OUTPUT_DIR}/." "$_"
-        
-        exit 0
+
 
