Update nightly docs action

diff --git a/.github/workflows/docs/generate-docs/action.yml b/.github/workflows/docs/generate-docs/action.yml
--- a/.github/workflows/docs/generate-docs/action.yml
+++ b/.github/workflows/docs/generate-docs/action.yml
@@ -9,22 +9,16 @@ inputs:
     description: "The documentation repository directory"
     required: true
     type: string
+  docs_file_name:
+    description: "The file name of the JSON docs file to update"
+    required: true
+    type: string
   skript_repo_dir:
     description: "The Skript repository directory"
     required: true
     type: string
   is_release:
-    description: "Designates whether to generate nightly or release documentation"
-    required: false
-    default: false
-    type: boolean
-  cleanup_pattern:
-    description: "A pattern designating which files to delete when cleaning the documentation output directory"
-    required: false
-    default: "*"
-    type: string
-  generate_javadocs:
-    description: "Designates whether to generate Javadocs for this documentation"
+    description: "Designates whether to generate release or nightly documentation"
     required: false
     default: false
     type: boolean
@@ -43,28 +37,13 @@ runs:
       env:
         DOCS_OUTPUT_DIR: ${{ inputs.docs_output_dir }}
         DOCS_REPO_DIR: ${{ inputs.docs_repo_dir }}
+        DOCS_FILE_NAME: ${{ inputs.docs_file_name }}
         SKRIPT_REPO_DIR: ${{ inputs.skript_repo_dir }}
         IS_RELEASE: ${{ inputs.is_release }}
         CLEANUP_PATTERN: ${{ inputs.cleanup_pattern }}
         GENERATE_JAVADOCS: ${{ inputs.generate_javadocs }}
       run: |
-        replace_in_directory() {
-          find $1 -type f -exec sed -i -e "s/$2/$3/g" {} \;
-        }
-
-        get_skript_version_of_directory() {
-          jq ".source.version" "$1/docs.json"
-        }
-
-        if [ -d "${DOCS_REPO_DIR}/docs/templates" ]
-        then
-          export SKRIPT_DOCS_TEMPLATE_DIR=${DOCS_REPO_DIR}/docs/templates
-        else # compatibility for older versions
-          export SKRIPT_DOCS_TEMPLATE_DIR=${DOCS_REPO_DIR}/doc-templates
-        fi
-
-        export SKRIPT_DOCS_OUTPUT_DIR=/tmp/generated-docs
-                  
+        # Generate docs.json from Skript repository
         cd $SKRIPT_REPO_DIR
         if [[ "${IS_RELEASE}" == "true" ]]; then
           ./gradlew genReleaseDocs javadoc
@@ -74,34 +53,20 @@ runs:
           ./gradlew genNightlyDocs
         fi
 
-        if [ -d "${DOCS_OUTPUT_DIR}" ]; then
-          if [[ "${GENERATE_JAVADOCS}" == "true" ]] || [[ "${IS_RELEASE}" == "true" ]] ; then
-              mkdir -p "${SKRIPT_DOCS_OUTPUT_DIR}/javadocs" && cp -a "./build/docs/javadoc/." "$_"
-          fi
-  
-          mkdir -p "/tmp/normalized-output-docs" && cp -a "${DOCS_OUTPUT_DIR}/." "$_"
-          mkdir -p "/tmp/normalized-generated-docs" && cp -a "${SKRIPT_DOCS_OUTPUT_DIR}/." "$_"
-  
-          output_skript_version=$(get_skript_version_of_directory "/tmp/normalized-output-docs")
-          generated_skript_version=$(get_skript_version_of_directory "/tmp/normalized-generated-docs")
+        # Sanitize expected existing file name
+        src_file = "${DOCS_FILE_NAME//\//-}.json"
 
-          replace_in_directory "/tmp/normalized-output-docs" "${output_skript_version}" "Skript"
-          replace_in_directory "/tmp/normalized-generated-docs" "${generated_skript_version}" "Skript"
-  
-          diff -qbr /tmp/normalized-output-docs /tmp/normalized-generated-docs || diff_exit_code=$?
-          # If diff exits with exit code 1, that means there were some differences
-          if [[ ${diff_exit_code} -eq 1 ]]; then
-            echo "DOCS_CHANGED=true" >> $GITHUB_OUTPUT
-            echo "Documentation has changed since last push"
-          else
-            echo "Documentation hasn't changed since last push"
-          fi
+        # Compare generated file vs existing file for changes
+        cd $DOCS_OUTPUT_DIR
+        diff -qb ${src_file} Skript-docs.json || diff_exit_code=$?
+        # If diff exits with exit code 1, that means there were some differences
+        if [[ ${diff_exit_code} -ne 1 ]]; then
+          echo "Documentation hasn't changed since last push"
+          exit
         else
-            echo "DOCS_CHANGED=true" >> $GITHUB_OUTPUT
-            echo "No existing documentation found"
+          echo "Documentation has changed since last push"
+          echo "DOCS_CHANGED=true" >> $GITHUB_OUTPUT
         fi
-        
-        rm -rf ${DOCS_OUTPUT_DIR}/${CLEANUP_PATTERN} || true
-        mkdir -p "${DOCS_OUTPUT_DIR}/" && cp -a "${SKRIPT_DOCS_OUTPUT_DIR}/." "$_"
 
-
+        # Replace existing file with generated file
+        mv Skript-docs.json ${src_file}
