fix file finding

diff --git a/.github/workflows/release-docs-v2.yml b/.github/workflows/release-docs-v2.yml
--- a/.github/workflows/release-docs-v2.yml
+++ b/.github/workflows/release-docs-v2.yml
@@ -25,14 +25,21 @@ jobs:
               run: |
                   ./gradlew genReleaseDocs
 
-            - name: Upload docs.json artifact
+            - name: Find docs.json
+              run: |
+                DOCS_JSON=$(find . -type f | grep docs.json | head -n 1)
+                if [ -z "$DOCS_JSON" ]; then
+                    echo "docs.json not found"
+                    exit 1
+                fi
+                echo "docs.json found at $DOCS_JSON"
+                echo "docs_json=$DOCS_JSON" >> $GITHUB_ENV
+
+            - name: Upload docs.json
               uses: actions/upload-artifact@v4
               with:
                   name: docs-json
-                  path: plugins/Skript/docs/docs.json
-
-            - name: List all files in the repo
-              run: find . -type f | grep docs.json
+                  path: ${{ env.docs_json }}
 
     deploy:
         name: Deploy Docs Update
